// @flow
export const SOME_API_RETURN_SUCCESS = 'SOME_API_RETURN_SUCCESS';
export const SEND_WEBSOCKET_MESSAGE = 'SEND_WEBSOCKET_MESSAGE';
export const SOCKET_MESSAGE_RECEIVED = 'SOCKET_MESSAGE_RECEIVED';
export const SOCKET_NOTIFICATION_RECEIVED = 'SOCKET_NOTIFICATION_RECEIVED';
